version: '3.8'

services:
  embed-server:
    build: .
    container_name: img-text-embed-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

